//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The WorkspaceLocatorService class provides a service to locate a Workspace given a smartpart and
// a WorkItem.
// 
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System.Collections.Generic;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.CompositeUI.SmartParts;
using FinanceApplicationCAB.Infrastructure.Interface.Services;

namespace FinanceApplicationCAB.Infrastructure.Library.Services
{
	public class WorkspaceLocatorService : IWorkspaceLocatorService
	{
		public IWorkspace FindContainingWorkspace(WorkItem workItem, object smartPart)
		{
			while (workItem != null)
			{
				foreach (KeyValuePair<string, IWorkspace> namedWorkspace in workItem.Workspaces)
				{
					if (namedWorkspace.Value.SmartParts.Contains(smartPart))
						return namedWorkspace.Value;
				}
				workItem = workItem.Parent;
			}
			return null;
		}
	}
}
