//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FinanceApplicationCAB.Infrastructure.Interface;
using FinanceApplicationCAB.Infrastructure.Interface.Constants;
using Microsoft.Practices.CompositeUI.EventBroker;

namespace FinanceApplicationCAB.Infrastructure.Module
{
	public partial class StockNewsViewPresenter : Presenter<IStockNewsView>
	{
		/// <summary>
		/// This method is a placeholder that will be called by the view when it has been loaded.
		/// </summary>
		public override void OnViewReady()
		{
			base.OnViewReady();
		}

		/// <summary>
		/// Close the view
		/// </summary>
		public void OnCloseView()
		{
			base.CloseView();
		}

		[EventSubscription(EventTopicNames.SelectedItemsChanged, ThreadOption.UserInterface)]
		public void OnSelectedItemsChanged(object sender, EventArgs eventArgs)
		{
			List<StockItem> selectedItems = this.WorkItem.State[StateKeys.SelectedItems] as List<StockItem>;

			if (selectedItems == null)
			{
				return;
			}

            if (selectedItems.Count > 0)
            {
                this.View.SetRssXml(selectedItems[0].ID);
            }
		}
	}
}

