//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// This interface defines the contract between the Presenter and its View, following the
// Model-View-Presenter pattern. 
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System.Collections.Generic;
using System;
namespace FinanceApplicationCAB.Infrastructure.Module
{
	public interface IStockPortfolioView
	{
		void AddValuationGroup(string caption, string name);
		void AddStockItem(StockItem item, string groupName);

		event EventHandler<EventArgs> SelectedItemsChanged;

		List<StockItem> SelectedItems
		{
			get;
		}

		event EventHandler<EventArgs> HoveredItemsChanged;

		List<StockItem> HoveredItems
		{
			get;
		}

		void ClearSelection();
		void SelectItem(StockItem stockItem);
	}
}

