
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FinanceApplicationCAB.Infrastructure.Module
{
	partial class StockPortfolioView
	{
		/// <summary>
		/// The presenter used by this view.
		/// </summary>
		private FinanceApplicationCAB.Infrastructure.Module.StockPortfolioViewPresenter _presenter = null;

		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (_presenter != null)
					_presenter.Dispose();

				if (components != null)
					components.Dispose();
			}

			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.radPanelBar = new Telerik.WinControls.UI.RadPanelBar();
			((System.ComponentModel.ISupportInitialize)(this.radPanelBar)).BeginInit();
			this.SuspendLayout();
			// 
			// radPanelBar
			// 
			this.radPanelBar.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
						| System.Windows.Forms.AnchorStyles.Left)
						| System.Windows.Forms.AnchorStyles.Right)));
			this.radPanelBar.BottomOffset = 0;
			this.radPanelBar.Caption = "Default Caption";
			this.radPanelBar.CaptionButtonRightOffset = 5;
			this.radPanelBar.CaptionHeight = 25;
			this.radPanelBar.CaptionTextFont = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
			this.radPanelBar.GroupStyle = Telerik.WinControls.PanelBarStyles.ListBar;
			this.radPanelBar.InitialOffset = 5;
			this.radPanelBar.LeftOffset = 0;
			this.radPanelBar.Location = new System.Drawing.Point(3, 3);
			this.radPanelBar.Name = "radPanelBar";
			this.radPanelBar.RightOffset = 0;
			this.radPanelBar.ShowCaptionImages = true;
			this.radPanelBar.Size = new System.Drawing.Size(325, 482);
			this.radPanelBar.SpacingBetweenItems = 5;
			this.radPanelBar.TabIndex = 0;
			this.radPanelBar.Text = "radPanelBar1";
			this.radPanelBar.TopOffset = 0;
			// 
			// StockPortfolioView
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.White;
			this.Controls.Add(this.radPanelBar);
			this.Name = "StockPortfolioView";
			this.Size = new System.Drawing.Size(331, 488);
			((System.ComponentModel.ISupportInitialize)(this.radPanelBar)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private Telerik.WinControls.UI.RadPanelBar radPanelBar;

	}
}

