
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FinanceApplicationCAB.Infrastructure.Module
{
	partial class StockPortfolioView
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (presenter != null)
					presenter.Dispose();

				if (components != null)
					components.Dispose();
			}

			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.radPageView = new Telerik.WinControls.UI.RadPageView();
            ((System.ComponentModel.ISupportInitialize)(this.radPageView)).BeginInit();
			this.SuspendLayout();
			// 
            // radPageView
			// 
            this.radPageView.Location = new System.Drawing.Point(3, 3);
            this.radPageView.Name = "radPageView";
            this.radPageView.Size = new System.Drawing.Size(325, 482);
            this.radPageView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radPageView.TabIndex = 0;
            this.radPageView.Text = "radPageView";
			// 
			// StockPortfolioView
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.radPageView);
			this.Name = "StockPortfolioView";
			this.Size = new System.Drawing.Size(331, 488);
            ((System.ComponentModel.ISupportInitialize)(this.radPageView)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private Telerik.WinControls.UI.RadPageView radPageView;
	}
}

