//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;

namespace FinanceApplicationCAB.Infrastructure.Interface
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
	public class ActionAttribute : Attribute
	{
		private string _actionName;

		public ActionAttribute(string actionName)
		{
			_actionName = actionName;
		}

		public string ActionName
		{
			get { return _actionName; }
			set { _actionName = value; }
		}
	}
}
