
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FinanceApplicationCAB.Infrastructure.Module
{
	partial class StockChartView
	{
		/// <summary>
		/// The presenter used by this view.
		/// </summary>
		private FinanceApplicationCAB.Infrastructure.Module.StockChartViewPresenter _presenter = null;

		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (_presenter != null)
					_presenter.Dispose();

				if (components != null)
					components.Dispose();
			}

			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			Telerik.Charting.Styles.Unit unit1 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit2 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit3 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit4 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit5 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit6 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit7 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit8 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit9 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit10 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit11 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit12 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit13 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit14 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit15 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit16 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.ChartSeries chartSeries1 = new Telerik.Charting.ChartSeries();
			Telerik.Charting.Styles.Unit unit17 = new Telerik.Charting.Styles.Unit();
			Telerik.Charting.Styles.Unit unit18 = new Telerik.Charting.Styles.Unit();
			this.radChart = new Telerik.WinControls.UI.RadChart();
			((System.ComponentModel.ISupportInitialize)(this.radChart)).BeginInit();
			this.SuspendLayout();
			// 
			// radChart
			// 
			this.radChart.Appearance.Corners = new Telerik.Charting.Styles.Corners(Telerik.Charting.Styles.CornerType.Rectangle, Telerik.Charting.Styles.CornerType.Rectangle, Telerik.Charting.Styles.CornerType.Rectangle, Telerik.Charting.Styles.CornerType.Rectangle, 6);
			unit1.Value = 417F;
			this.radChart.Appearance.Dimensions.Height = unit1;
			unit2.Value = 558F;
			this.radChart.Appearance.Dimensions.Width = unit2;
			unit3.Value = 3F;
			unit4.Value = 5F;
			unit5.Value = 3F;
			unit6.Value = 10F;
			this.radChart.ChartTitle.Appearance.Dimensions.Paddings = new Telerik.Charting.Styles.ChartPaddings(unit3, unit4, unit5, unit6);
			this.radChart.ChartTitle.TextBlock.Text = "Day % Change";
			this.radChart.DataGroupColumn = null;
			this.radChart.Dock = System.Windows.Forms.DockStyle.Fill;
			this.radChart.Legend.Appearance.Border.Color = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227)))));
			unit7.Value = 0F;
			unit8.Value = 1F;
			unit9.Value = 1F;
			unit10.Value = 10F;
			this.radChart.Legend.Appearance.Dimensions.Paddings = new Telerik.Charting.Styles.ChartPaddings(unit7, unit8, unit9, unit10);
			this.radChart.Location = new System.Drawing.Point(0, 0);
			this.radChart.Name = "radChart";
			this.radChart.PlotArea.Appearance.Corners = new Telerik.Charting.Styles.Corners(Telerik.Charting.Styles.CornerType.Round, Telerik.Charting.Styles.CornerType.Round, Telerik.Charting.Styles.CornerType.Round, Telerik.Charting.Styles.CornerType.Round, 6);
			this.radChart.PlotArea.Appearance.SeriesPalette = "Colorful";
			this.radChart.PlotArea.XAxis.Appearance.MajorGridLines.Visible = false;
			this.radChart.PlotArea.XAxis.Appearance.ValueFormat = Telerik.Charting.Styles.ChartValueFormat.General;
			unit11.Value = 2F;
			this.radChart.PlotArea.XAxis.AxisLabel.Appearance.Dimensions.Height = unit11;
			unit12.Value = 4F;
			this.radChart.PlotArea.XAxis.AxisLabel.Appearance.Dimensions.Width = unit12;
			this.radChart.PlotArea.XAxis.AxisLabel.Appearance.Position.X = 244.5F;
			this.radChart.PlotArea.XAxis.AxisLabel.Appearance.Position.Y = 409.832F;
			this.radChart.PlotArea.XAxis.AxisLabel.TextBlock.Appearance.Position.X = 2F;
			this.radChart.PlotArea.XAxis.AxisLabel.TextBlock.Appearance.Position.Y = 2F;
			this.radChart.PlotArea.XAxis.AxisLabel.TextBlock.Appearance.TextProperties.Font = new System.Drawing.Font("Arial", 10F);
			this.radChart.PlotArea.XAxis.MaxValue = 7;
			this.radChart.PlotArea.XAxis.MinValue = 1;
			this.radChart.PlotArea.XAxis.Step = 1;
			this.radChart.PlotArea.YAxis.Appearance.ValueFormat = Telerik.Charting.Styles.ChartValueFormat.Number;
			unit13.Value = 2F;
			this.radChart.PlotArea.YAxis.AxisLabel.Appearance.Dimensions.Height = unit13;
			unit14.Value = 4F;
			this.radChart.PlotArea.YAxis.AxisLabel.Appearance.Dimensions.Width = unit14;
			this.radChart.PlotArea.YAxis.AxisLabel.Appearance.Position.X = -8.657795F;
			this.radChart.PlotArea.YAxis.AxisLabel.Appearance.Position.Y = 217F;
			this.radChart.PlotArea.YAxis.AxisLabel.TextBlock.Appearance.Position.X = 2F;
			this.radChart.PlotArea.YAxis.AxisLabel.TextBlock.Appearance.Position.Y = 2F;
			this.radChart.PlotArea.YAxis.AxisLabel.TextBlock.Appearance.TextProperties.Font = new System.Drawing.Font("Arial", 10F);
			this.radChart.PlotArea.YAxis.Step = 20;
			unit15.Value = 2F;
			this.radChart.PlotArea.YAxis2.AxisLabel.Appearance.Dimensions.Height = unit15;
			unit16.Value = 4F;
			this.radChart.PlotArea.YAxis2.AxisLabel.Appearance.Dimensions.Width = unit16;
			this.radChart.PlotArea.YAxis2.AxisLabel.Appearance.Position.X = 465F;
			this.radChart.PlotArea.YAxis2.AxisLabel.Appearance.Position.Y = 217F;
			this.radChart.PlotArea.YAxis2.AxisLabel.TextBlock.Appearance.Position.X = 2F;
			this.radChart.PlotArea.YAxis2.AxisLabel.TextBlock.Appearance.Position.Y = 2F;
			this.radChart.PlotArea.YAxis2.AxisLabel.TextBlock.Appearance.TextProperties.Font = new System.Drawing.Font("Arial", 10F);
			this.radChart.PlotArea.YAxis2.MaxValue = 7;
			this.radChart.PlotArea.YAxis2.MinValue = 1;
			this.radChart.PlotArea.YAxis2.Step = 1;
			chartSeries1.Appearance.FillStyle.MainColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
			chartSeries1.Appearance.FillStyle.SecondColor = System.Drawing.Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(194)))), ((int)(((byte)(194)))));
			unit17.Value = 0F;
			chartSeries1.Appearance.PointMark.Dimensions.Height = unit17;
			unit18.Value = 0F;
			chartSeries1.Appearance.PointMark.Dimensions.Width = unit18;
			chartSeries1.Name = "Change";
			this.radChart.Series.Add(chartSeries1);
			this.radChart.SeriesPalette = "Colorful";
			this.radChart.Size = new System.Drawing.Size(558, 417);
			this.radChart.TabIndex = 0;
			// 
			// StockChartView
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.radChart);
			this.Name = "StockChartView";
			this.Size = new System.Drawing.Size(558, 417);
			((System.ComponentModel.ISupportInitialize)(this.radChart)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private Telerik.WinControls.UI.RadChart radChart;
	}
}

