//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FinanceApplicationCAB.Infrastructure.Interface.Constants
{
	/// <summary>
	/// Constants for event topic names.
	/// </summary>
	public class EventTopicNames
	{
		/// <summary>
		/// Event fired to tell the shell to update the status panel
		/// </summary>
		public const string StatusUpdate = "StatusUpdate";
		public const string SelectedItemsChanged = "SelectedItemsChanged";
		public const string HoveredItemsChanged = "HoveredItemsChanged";
	}
}
